### ISSUE TITLE
Targeting multiple Subcraft Rotate signs in a single bugs out

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#133]
**Describe the bug**
When I target two or more Subcraft Rotate signs with a single Remote sign, one rotates while the rest does not, returning "Already Rotating"

**To Reproduce**

1. Make a craft containing two or more Subcraft Rotate signs (I used Turret for my subcrafts on the parent craft, which was Elevator type)
2. Place a single Remote sign targeting all Subcraft Rotate signs.
3. pilot the craft and click the remote sign
4. Watch as only one rotating subcraft rotates.

**Expected behavior**
All subcrafts should rotate

**Screenshots**
![2019-07-07_16 38 32](https://user-images.githubusercontent.com/11066794/60769915-bb28c400-a0d5-11e9-9e88-9d899fe72126.png)

**Versions (please complete the following information):**
 - Movecraft: 7.0.0 prerelease 9
 - Java JDK 8.0.1
 - Minecraft 1.10.2

**Additional context**

**Comment by TylerS1066** [comment]
I believe this issue is far deeper than remote signs alone and has to do with the core way that movecraft keeps track of crafts and players, and fixing this would require a major redo of the internals.  I think we decided upon keeping this limitation as it is because of the amount of an overhaul this would take to "fix".
