### ISSUE TITLE
Blade block resource collecting chest

### ISSUE THREAD

**Issue by jamesol1** [APDevTeam/Movecraft#198]
A chest that would automatically collect blade block harvested resources. Or a setting that would give the resources to the pilot. I tried using hoppers for my drill bit but they dont seem to collect resources when being used as blade blocks.

Would be very handy for a drill 'vehicle' i have made.

**Comment by cccm5** [comment]
If you're noticing that harvested blocks aren't being placed into *any* chests, that's a bug. Otherwise, this topic has been something that I've struggled to find the best solution to. In the past when I redid harvesting, I couldn't decide the best way to do this, so I opted to have it go into any chest on the craft. Other ideas where signs, and all possible inventory blocks. I still don't know the best way, but if you (or anyone else) have any Idea's I'm all for it.

**Comment by jamesol1** [comment]
Please forgive me, i did not know the feature was added, didnt notice it being mentioned on the wiki. It seems to work fine. Although that issue with 'descend' not working with blade blocks is still reaccuring.

**Comment by cccm5** [comment]
What's happening is that while cruising, the craft moves at intervals as set in the craft type. Harvester blades look and see if the new position they would be in is a harvest-able block, but the blocks behind harvest blade blocks do not. So at the moment, if you want to cruise while harvesting, you need to have a layer of harvesting blocks equal in size to the distance you move while cruising

**Comment by jamesol1** [comment]
Ah that makes sense! I have changed my cruiseskipblocks to 1 works fine. No need to correct/add anything. Drills shouldnt really be skipping too many blocks anyways.
