### ISSUE TITLE
POI data mismatch

### ISSUE THREAD

**Issue by mhbates** [APDevTeam/Movecraft#451]
**Describe the bug**
I noticed an occasional POI data mismatch error when using ships. It almost seems random, I haven't figured out what specifically causes it.

Example of the error:

`[09:02:14 ERROR]: POI data mismatch: never registered at BlockPosition{x=-74, y=64, z=-79}`

**Versions (please complete the following information):**
 - Movecraft: 8 alpha 4
 - Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9)
 - Minecraft 1.16.5 (Airplane)

**Comment by Coder-TheSid** [comment]
Try use MoveCraft 7.

I guess MoveCraft 8 just for 1.17+.

**Comment by TylerS1066** [comment]
Movecraft 7 will not work on 1.16.5.  I'm not sure what this issue is, and honestly I'm not sure if it has any bad effects.  I've seen the message before but I've not yet had any world corruption or problems with Movecraft 8, so it may just be a useless warning.  Regardless, this is not something I'd know how to fix.

**Comment by TylerS1066** [comment]
I've seen no issues on this, feel free to open a new issue if there arise any.
