### ISSUE TITLE
Broken blocks on Piloted Crafts

### ISSUE THREAD

**Issue by PinkiBaron** [APDevTeam/Movecraft#490]
I looked thru the project thing and couldn't find anything saying this was intentional, so correct me if this ISN'T a bug
Piloted crafts don't prevent you from breaking blocks, like it has in the past. (where you try breaking a block, and it says "part of a piloted craft")

Again, correct me if this ISNT a bug :)

**Comment by goodroach** [comment]
This actually is a bug, in the server config for mine, the "protectPilotedCrafts" variable is set to true. However you can break the blocks in ships.

**Comment by TylerS1066** [comment]
I've confirmed this bug also happens on my 1.14.4 test server, but I'm unsure of why right now.

**Comment by TylerS1066** [comment]
This problem is throwing me for a loop.  For some reason, when I check over the hitbox of the craft the broken block no longer is in the hitbox.  When I use my debug plugin ([MidasCraft](https://github.com/TylerS1066/MidasCraft)), it does show the block as part of the hitbox.

My suspicion is that it might be some addon or other listener interfering, but I'm not sure.
