### ISSUE TITLE
Where is the download link on the development site?

### ISSUE THREAD

**Issue by FrozenBeard** [APDevTeam/Movecraft#50]
https://travis-ci.org/APDevTeam/Movecraft

I cant see anywhere to actually download each build?

**Comment by FrozenBeard** [comment]
Feel free to ping me a copy, you have me on discord already. I can throw it on my test server with 30+ players to test ships on seas.

**Comment by cccm5** [comment]
Travis doesn't build actual jar's unless a commit is made with a tag. Otherwise, it just tests the code. I try to release pre-releases when I fix most known bugs, and at the moment there is a bug with subcraft rotate signs causing them to not function. When that is fixed, the next pre-release will most likley be put in the release category.
