### ISSUE TITLE
Jar files

### ISSUE THREAD

**Issue by tskopen** [APDevTeam/Movecraft#509]
This isn't an issue but I just ask if you could name the jar more than just movecraft, like the version. for it's easier to remember which one I downloaded. though if you cant do this for some reason like the plugin constantly reads the jar or something that's fine.

**Comment by TylerS1066** [comment]
From a developer prospective, this has been a conscious choice on our part to make it easier when debugging problems.  Instead of having to copy over the file and then delete the old one, we can just copy over one to overwrite the old one.

For dev builds, we've appended the full commit ID to the jar name, for example: `Movecraft_5a03180f265784059712a10602906481681c85e4.jar`.  We did this to help show exactly what dev builds server owners are using.

For alpha/beta/full releases, I think it does make sense to append the version number to it, and I'll try to remember to do that in the future.
