### ISSUE TITLE
Chest Penalty Does Not Work

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/Movecraft#555]
**Describe the bug**
The .craft variable chestPenalty does not work. Is it supposed to be scaled to 0.0 to 1.0? Or can I make it a number like 3.0? 

**To Reproduce**
1. Make a dynamicLagSpeed craft
2. Set the chestPenalties to various numbers
3. Speed does not change in a significant way

**Expected behavior**
chestPenalty should work by decerasing the speed of the craft the more chests it has. (Though it should also extend as a list of blocks rather than just chests...)

**Versions (please complete the following information):**
 - Movecraft: 8.0.0 alpha 9
 - Addons: Movecraft Combat alpha 6
 - Java JDK 16
 - Minecraft 1.16.5

**Comment by TylerS1066** [comment]
This is intentional behavior for a `dynamicLagSpeed` craft:
https://github.com/APDevTeam/Movecraft/blob/120d3e23f2b77252e10be0b2defa30b4cd51d4e9/modules/Movecraft/src/main/java/net/countercraft/movecraft/craft/BaseCraft.java#L437

The chest penalty is a legacy lag prevention method based on the (incorrect) assumption that the largest source of craft movement lag is moving the large inventories of chests, when in fact all tiles are equal (except signs are worse due to internal Movecraft processing).
