### ISSUE TITLE
Craft#getHitbox() Returns empty

### ISSUE THREAD

**Issue by Zeltuv** [APDevTeam/Movecraft#560]
When I listen to the `CraftDetectEvent` and call the function `CraftDetectEvent#getCraft()` then the function `Craft#getHitbox()` it returns an empty Hitbox, so I would like to know what could cause this bug or if it's something normal and I miss did something. Thanks for your help in advance.

**Comment by TylerS1066** [comment]
`CraftDetectEvent` is only called in `DetectionTask#get()`, shortly after `craft/setHitBox(hitbox)` is called, so I'm not sure why you are seeing this behavior.

Many of our addons, including [Movecraft-CoreProtect](https://github.com/APDevTeam/Movecraft-CoreProtect/blob/main/src/main/java/net/countercraft/movecraft/coreprotect/movecraftcoreprotect/listeners/CraftDetectListener.java) use this same method to get full hitboxes on detection, and I can confirm that it is working.  In fact, [Movecraft itself](https://github.com/APDevTeam/Movecraft/blob/main/modules/Movecraft/src/main/java/net/countercraft/movecraft/sign/CruiseSign.java) uses the detection event internally and it works, so I'm not sure what the problem is in your setup.

If you could share a repository we might be able to help you diagnose the code problem.

**Comment by Zeltuv** [comment]
I unfortunately can't share the repository but I can show you the code piece that proves me the hitbox is empty, also I can share specific files if you need. 

https://hastebin.com/ajaqibowes.kotlin

**Comment by Zeltuv** [comment]
Also I need to precise that I'm using a fork of your plugin, do you think it can come from there ?

**Comment by TylerS1066** [comment]
Your code is printing that when the hitbox is not empty.

In addition, we provide no support for forks since they commonly are running very outdated code bases.  I recommend you file issues on their pages or switch to our version.

**Comment by Zeltuv** [comment]
Damn sorry I didn't took a good look
