### ISSUE TITLE
Burning furnances & Double chests

### ISSUE THREAD

**Issue by Appw0** [APDevTeam/Movecraft#60]
It would be neat if furnaces would play the burning animation when being used for fuel. Also the ability to transport double chests (if possible) Just some ideas for enhancement.

**Comment by altrisi** [comment]
I think double chests would be difficult because there are a lot of visual bugs with normal chests while moving, but I think burning furnace is a bit easier, because it's about changing the block ID (the light it emits is different, it would probably be without light until a solution for light is found).

**Comment by TylerS1066** [comment]
With the rewrite of detection, double chests are moved with crafts.
