### ISSUE TITLE
Paper build update breaking Movecraft internal systems?

### ISSUE THREAD

**Issue by tskopen** [APDevTeam/Movecraft#608]
**Describe the bug**
Paper update messed with movecraft internal systems I believe
**To Reproduce**
1. Use paper build #161 

**Expected behavior**
[helm] doesnt work
Movecraft crashs server on start up "[19:07:09] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached"
Note: Ive consulted my server host and we have enough CPU, though movecraft is taking up the entire containers thread limit by itself.
More lag then normal

**Versions (please complete the following information):**
 - Movecraft: 1.20.1 Beta 2
 - Addons: Movecraft-Combat v1.0.0, Movecraft-Repair v1.0.0, movecraft-cannons github build commit [fe3feba]
 - Java Java 17
 - Minecraft 1.20.1

**Additional context**
All issues didnt happen on previous paper versions.
![image](https://github.com/APDevTeam/Movecraft/assets/80185495/3e1daa66-37db-4610-bcba-080dc716c32d)
Something like this is causing it I believe

**Comment by TylerS1066** [comment]
This is not an issue with Movecraft or a Paper update, running Paper 1.20.1 Build 161 and Movecraft Beta 2, I do not have issues with piloting, rotating, and cruising.

> movecraft is taking up the entire containers thread limit by itself

Re-reading your initial issue report, this issue is because of artificial limits imposed on you by your server host.  They are (likely) correct in that you "have enough CPU", but for some reason they are artificially imposing a thread limit on your server.  Movecraft's processing system will spawn as many threads as your CPU can handle to utilize as much of your processor's performance as possible.  I'd recommend contacting your server host and having them remove their artificial limit or finding a better host.
