### ISSUE TITLE
Right-clicking cannot make the ship execute

### ISSUE THREAD

**Issue by 7bloice** [APDevTeam/Movecraft#628]
In the new version, right-clicking can change the notice board, but we need to right-click to make the ship move straight. what can i do 1.20.1

**Comment by TylerS1066** [comment]
Which Movecraft version are you using?  This was already fixed in [#sign](https://github.com/APDevTeam/Movecraft/pull/618/commits/2342c87fe9aa57158238aadd8c08152903bd9e5d), but there hasn't been a beta release since then.

I'd recommend downloading the [latest actions build for 1.20.4](https://github.com/APDevTeam/Movecraft/actions/runs/8211377041).
