### ISSUE TITLE
1.20.6 Paper Crash

### ISSUE THREAD

**Issue by Nikkilectric** [APDevTeam/Movecraft#650]
**Describe the bug**
When starting the latest [dev build](https://github.com/APDevTeam/Movecraft/actions/runs/9438979699), The plugin crashes on start

**To Reproduce**
1. Start the server on the latest [dev version](https://github.com/APDevTeam/Movecraft/actions/runs/9438979699) 

**Expected behavior**
The plugin should start up correctly, and not show up as beta_2

**Logs**
https://pastebin.com/Su4iR9Y8

**Versions (please complete the following information):**
 - Movecraft: Latest Dev Build (774013ace90033f404e02d7e29d45aa8475bbb26)
 - Addons: Movecraft-Combat (Latest Dev build), Movecraft Worldguard, Movecraft Cannons
 - Java JDK 21
 - Minecraft 1.20.6

**Comment by TylerS1066** [comment]
The linked dev build (while the latest to run), is not the latest in the code base.  I created the `1.20.4` branch and triggered that dev build so that all the people asking for a 1.20.4 download had something.

The correct dev build for 1.20.6 is currently [this one](https://github.com/APDevTeam/Movecraft/actions/runs/9432845592), which works on the latest paper (140) and purpur (2232).

**Comment by Nikkilectric** [comment]
Ah, sorry. Thank you!
