### ISSUE TITLE
It doesn't load, crashes with an error in the console

### ISSUE THREAD

**Issue by Sauron971** [APDevTeam/Movecraft#656]
**Describe the bug**
I have installed all the addons for MoveCraft, except Towny, when loading plugins, they all give an error

**Versions (please complete the following information):**
 - Movecraft: Movecraft_8.0.0_beta-3
 - Addons: Movecraft-Cannons_1.0.0_beta-1; Movecraft-Combat_2.0.0_beta-4; Movecraft-CoreProtect_1.0.0_beta-1; Movecraft-Repair_1.0.0_beta-4; Movecraft-Warfare_1.0.0_beta-3; Movecraft-WorldGuard_1.0.0_beta-3
 - Java 21
 - Minecraft 1.20.6

Errors here: https://pastebin.com/YZbHsSp9

**Comment by TylerS1066** [comment]
As mentioned in the first error, Movecraft failed to find support for the Minecraft version `craftbukkit`:
```
[15:34:32 INFO]: [Movecraft] Loading support for craftbukkit
[15:34:32 WARN]: java.lang.ClassNotFoundException: net.countercraft.movecraft.compat.craftbukkit.IWorldHandler
    [...]
[15:34:32 ERROR]: [Movecraft] Could not find support for this version.
```

As mentioned in the [8.0.0 beta 3 release notes](https://github.com/APDevTeam/Movecraft/releases/tag/8.0.0_beta-3), Paper 1.20.6 (and it's forks, such as Purpur) were not yet supported due to [Paper making the "hard fork" and changing how various internal Spigot systems operated](https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/).  The details of the issue can be found in #647, but we have switched to the Paper systems in the recent dev builds, such as [this one](https://github.com/APDevTeam/Movecraft/actions/runs/9601994906).

Following that, it looks like the datapack isn't loading.  If that persists after you fix the version incompatibility, check out [our FAQ](https://github.com/APDevTeam/Movecraft/wiki/Frequently-Asked-Questions#movecraft-8-or-its-addons-wont-load) on how to resolve it.
