### ISSUE TITLE
Factions support

### ISSUE THREAD

**Issue by eirikh1996** [APDevTeam/Movecraft#72]
Suggestion: Add support for the Factions plugin

**Comment by FrozenBeard** [comment]
Simple clans support would be better :muscle:

**Comment by TylerS1066** [comment]
Due to the new spur of Addon plugins which we will be working on, it is planned that WorldGuard support will be removed from Movecraft itself and housed in a secondary Movecraft-WG (MCWG) plugin at a later date.  This will work as a template for other protection plugin addons (such as Movecraft-PlotSquared, or Movecraft-Factions).  I cannot guarantee if we will code protection for Simple Clans or Factions, but it should be fairly simple for a plugin developer to implement it.

**Comment by eirikh1996** [comment]
> Due to the new spur of Addon plugins which we will be working on, it is planned that WorldGuard support will be removed from Movecraft itself and housed in a secondary Movecraft-WG (MCWG) plugin at a later date. This will work as a template for other protection plugin addons (such as Movecraft-PlotSquared, or Movecraft-Factions). I cannot guarantee if we will code protection for Simple Clans or Factions, but it should be fairly simple for a plugin developer to implement it.

As for Factions, I have already made this addon here: https://www.spigotmc.org/resources/movecraft-factions.72188/
