### ISSUE TITLE
Latest in API builds outdated version

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/Movecraft#724]
**Describe the bug**
The movecraft build when you set the build.gradle to the latest version of this movecraft, it will set the movecraft to a beta 3 instead of a beta 5 version

**To Reproduce**
1. Follow the Gradle instructions for movecraft
2. View the packages 

**Expected behavior**
This should use the beta 5 version of movecraft.

**Screenshots**
![image](https://github.com/user-attachments/assets/66bed693-5ec5-4ecb-a4e2-b2dc4052ff97)

**Additional context**
This is a gradle problem.
Pastebin link: https://pastebin.com/F1bM9TTw

**Comment by TylerS1066** [comment]
Check how [Movecraft-CoreProtect](https://github.com/APDevTeam/Movecraft-CoreProtect/blob/main/build.gradle.kts) depends on Movecraft, that is our reference for how to develop add-ons and where [our API documentation page](https://github.com/APDevTeam/Movecraft/wiki/Documentation) is derived from.  Loading that in IntelliJ idea, the only gradle dependency it lists is `net.countercraft.movecraft:8.0.0_beta-5`.  This is likely something in your gradle config, which will be different because you are using Groovy DSL instead of Kotlin DSL.
